import {GithubLogoIcon, LinkedinLogoIcon , ReadCvLogoIcon} from "@phosphor-icons/react";

function SiteFooter() {
  return (
    <footer className="site-footer">
      <p>
          Content and layout are generated by your on-device browser&#39;s AI.
      </p>
      <div className="footer-links">
        <a
          href="https://github.com/Luke-Cheng"
          target="_blank"
          rel="noreferrer"
          aria-label="GitHub"
          title="GitHub/Luke-Cheng"
        >
          <GithubLogoIcon fontSize="inherit" aria-hidden="true" />
        </a>
        <a
          href="https://www.linkedin.com/in/luke-cheng/"
          target="_blank"
          rel="noreferrer"
          aria-label="LinkedIn"
          title="In/Luke-Cheng"
        >
          <LinkedinLogoIcon fontSize="inherit" aria-hidden="true" />
        </a>
        <a
          href="/portfolio.md"
          aria-label="Resume"
          title="Luke-Cheng-Resume.md"
        >
          <ReadCvLogoIcon fontSize="inherit" aria-hidden="true" />
        </a>
      </div>
    </footer>
  );
}

export default SiteFooter;
